# Generated by Django 2.2.3 on 2019-07-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assign_to',
            field=models.CharField(default='Unassigned', max_length=45),
        ),
    ]
