# Generated by Django 2.2.3 on 2019-07-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20190729_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='viewed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
