# Generated by Django 2.2.3 on 2019-08-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_ticket_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='desc',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ts',
            field=models.TextField(default='NA'),
        ),
    ]
