# Generated by Django 2.2.3 on 2019-08-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20190805_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='desc',
            field=models.TextField(default='NA', null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ts',
            field=models.TextField(default='NA', null=True),
        ),
    ]
