# Generated by Django 2.2.3 on 2019-07-29 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept_assignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_user_dept', to='main.Employee'),
        ),
        migrations.AlterField(
            model_name='store_assignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_user_store', to='main.Employee'),
        ),
    ]
