# Generated by Django 2.2.3 on 2019-08-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_employee_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='stores',
            field=models.ManyToManyField(related_name='assigned_employees', to='main.Store'),
        ),
        migrations.DeleteModel(
            name='Store_Assignment',
        ),
    ]
