# Generated by Django 2.2.3 on 2019-08-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190801_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='stores',
        ),
        migrations.AddField(
            model_name='store',
            name='employees',
            field=models.ManyToManyField(related_name='stores_assigned', to='main.Employee'),
        ),
    ]
