# Generated by Django 2.2.3 on 2019-08-02 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190801_1828'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dept_Assignment',
        ),
    ]
